# Generated by Django 4.1.7 on 2023-02-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=100)),
                ('cards', models.CharField(max_length=100)),
            ],
        ),
    ]
